name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/image-43.png
    - assets/page-1/images/image-35.png
    - assets/page-1/images/image-9.png
    - assets/page-1/images/icon-arrow-forward.png
    - assets/page-1/images/image-16.png
    - assets/page-1/images/image-16-HBv.png
    - assets/page-1/images/image-12.png
    - assets/page-1/images/image-49.png
    - assets/page-1/images/image-15.png
    - assets/page-1/images/image-29.png
    - assets/page-1/images/image-15-8gx.png
    - assets/page-1/images/image-46.png
    - assets/page-1/images/image-17.png
    - assets/page-1/images/image-15-gUG.png
    - assets/page-1/images/image-40.png
    - assets/page-1/images/image-7.png
    - assets/page-1/images/image-26.png
    - assets/page-1/images/image-19.png
    - assets/page-1/images/image-5.png
    - assets/page-1/images/image-8.png
    - assets/page-1/images/image-28.png
    - assets/page-1/images/image-8-j1J.png
    - assets/page-1/images/image-18.png
    - assets/page-1/images/image-9-3zG.png
    - assets/page-1/images/material-symbols-edit.png
    - assets/page-1/images/image-45.png
    - assets/page-1/images/image-4.png
    - assets/page-1/images/ellipse-1-bg.png
    - assets/page-1/images/image-2.png
    - assets/page-1/images/image-54.png
    - assets/page-1/images/image-14.png
    - assets/page-1/images/image-47.png
    - assets/page-1/images/image-18-GYp.png
    - assets/page-1/images/image-15-Zip.png
    - assets/page-1/images/image-16-U7S.png
    - assets/page-1/images/abc-removebg-preview-1.png
    - assets/page-1/images/image-26-9Da.png
    - assets/page-1/images/image-39.png
    - assets/page-1/images/image-5-kWC.png
    - assets/page-1/images/image-24.png
    - assets/page-1/images/image-39-2dv.png
    - assets/page-1/images/image-57.png
    - assets/page-1/images/image-17-oyS.png
    - assets/page-1/images/image-51.png
    - assets/page-1/images/image-16-Pha.png
    - assets/page-1/images/image-15-KHz.png
    - assets/page-1/images/image-15-M1S.png
    - assets/page-1/images/image-4-sVa.png
    - assets/page-1/images/material-symbols-account-circle.png
    - assets/page-1/images/image-9-hRJ.png
    - assets/page-1/images/image-48.png
    - assets/page-1/images/image-50.png
    - assets/page-1/images/image-20.png
    - assets/page-1/images/material-symbols-account-circle-W1v.png
    - assets/page-1/images/image-16-vXS.png
    - assets/page-1/images/image-4-zSk.png
    - assets/page-1/images/material-symbols-account-circle-KSQ.png
    - assets/page-1/images/image-31.png
    - assets/page-1/images/image-8-ptx.png
    - assets/page-1/images/image-44.png
    - assets/page-1/images/image-41.png
    - assets/page-1/images/image-38.png
    - assets/page-1/images/image-23.png
    - assets/page-1/images/image-27.png
    - assets/page-1/images/image-6.png
    - assets/page-1/images/image-2-Cwz.png
    - assets/page-1/images/image-11.png
    - assets/page-1/images/image-21.png
    - assets/page-1/images/image-32.png
    - assets/page-1/images/image-4-x3z.png
    - assets/page-1/images/image-10.png
    - assets/page-1/images/image-54-Q4Q.png
    - assets/page-1/images/image-58.png
    - assets/page-1/images/image-37.png
    - assets/page-1/images/image-34.png
    - assets/page-1/images/image-36.png
    - assets/page-1/images/image-25.png
    - assets/page-1/images/image-32-UyN.png
    - assets/page-1/images/image-15-3ma.png
    - assets/page-1/images/material-symbols-account-circle-PqS.png
    - assets/page-1/images/image-52.png
    - assets/page-1/images/image-54-wc4.png
    - assets/page-1/images/image-56.png
    - assets/page-1/images/image-19-Hvp.png
    - assets/page-1/images/image-8-ciC.png
    - assets/page-1/images/image-5-nMn.png
    - assets/page-1/images/image-19-3gt.png
    - assets/page-1/images/image-56-rAU.png
    - assets/page-1/images/image-56-5L4.png
    - assets/page-1/images/image-22.png
    - assets/page-1/images/image-16-NCY.png
    - assets/page-1/images/image-19-X9J.png
    - assets/page-1/images/image-13.png
    - assets/page-1/images/image-5-6Xi.png
    - assets/page-1/images/image-42.png
    - assets/page-1/images/material-symbols-account-circle-GZv.png
    - assets/page-1/images/image-24-gwi.png
    - assets/page-1/images/image-56-MHA.png
    - assets/page-1/images/image-58-gaL.png
    - assets/page-1/images/image-54-YMW.png
    - assets/page-1/images/image-18-44x.png
    - assets/page-1/images/image-18-ruE.png
    - assets/page-1/images/image-42-Bxk.png
    - assets/page-1/images/image-33.png
    - assets/page-1/images/image-27-A5n.png
    - assets/page-1/images/image-54-QKJ.png
    - assets/page-1/images/image-52-umr.png
    - assets/page-1/images/image-41-TXe.png
    - assets/page-1/images/image-7-dnQ.png
    - assets/page-1/images/image-19-a5E.png
    - assets/page-1/images/image-16-HAG.png
    - assets/page-1/images/image-52-eDN.png
    - assets/page-1/images/material-symbols-account-circle-D4c.png
    - assets/page-1/images/image-32-Rip.png
    - assets/page-1/images/image-7-3pc.png
    - assets/page-1/images/image-58-3yi.png
    - assets/page-1/images/image-41-vPz.png
    - assets/page-1/images/abc-removebg-preview-1-W8Q.png
    - assets/page-1/images/image-15-uDr.png
    - assets/page-1/images/image-57-UZ6.png
    - assets/page-1/images/image-52-JQG.png
    - assets/page-1/images/image-56-XnY.png
    - assets/page-1/images/image-54-oBe.png
    - assets/page-1/images/image-58-spU.png
    - assets/page-1/images/image-24-ctG.png
    - assets/page-1/images/image-54-uig.png
    - assets/page-1/images/image-16-jzg.png
    - assets/page-1/images/icon-arrow-forward-5w6.png
    - assets/page-1/images/image-56-vfS.png
    - assets/page-1/images/image-18-m7e.png
    - assets/page-1/images/image-16-dzp.png
    - assets/page-1/images/image-10-XhS.png
    - assets/page-1/images/image-4-824.png
    - assets/page-1/images/image-41-beQ.png
    - assets/page-1/images/image-6-4he.png
    - assets/page-1/images/image-5-qhz.png
    - assets/page-1/images/image-8-khE.png
    - assets/page-1/images/image-7-Rbe.png
    - assets/page-1/images/image-18-Eic.png
    - assets/page-1/images/image-2-1fE.png
    - assets/page-1/images/image-8-pgQ.png
    - assets/page-1/images/image-5-JkY.png
    - assets/page-1/images/image-9-CZv.png
    - assets/page-1/images/image-12-eu6.png
    - assets/page-1/images/material-symbols-edit-Btc.png
    - assets/page-1/images/image-4-A1W.png
    - assets/page-1/images/image-19-fsn.png
    - assets/page-1/images/image-11-rkx.png
    - assets/page-1/images/image-2-f3E.png
    - assets/page-1/images/image-32-HSY.png
    # - assets/page-1/images/image-15-ZVJ.png
    - assets/page-1/images/image-15-ZVJ.png
    # - assets/page-1/images
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
